### ISSUE TITLE
vraptor maturity level.

### ISSUE THREAD

**Issue by masumcse1** [caelum/vraptor4#1028]
actually long time , i am using JSF. Now i want to use vraptor. is vraptor4 is ready for large scale 
financial application development ?

**Comment by Turini** [comment]
Hi @masumcse1, TLDR yes it is :) There is several projects using VRaptor, including [GUJ](http://www.guj.com.br/) and [Alura](https://www.alura.com.br/), both maintained from the same educational company that maintains this framework. The company is called Caelum, a famous training company in Brazil, visible on https://www.caelum.com.br/ (pt_BR only, sorry, and actually this site is also running on VRaptor). If you're going to create a large scale app, we strongly recommend the usage of an application server, such as WildFly (my favorite choice) or Glassfish (RI impl). The CDI usage brings to VRaptor a convenient capability to integrate really well with other Java EE specs, such as JPA, BeanValidation, EJB, JMS and many others. Besides that, we have an amazing, friendly and helpful community, and a fast support. Best regards

**Comment by csokol** [comment]
I think we have a lot of successful use cases of VRaptor. VivaReal
<http://vivareal.com.br>, for example, is the largest real state market
place from Brazil and uses VRaptor for several internal services,
responding millions of requests each day.

**Comment by masumcse1** [comment]
yes , also my best choice is wildfly 10. 

I interested to know that is there any open source web application built using vraptor 4 ?

**Comment by Turini** [comment]
AFAIK there is Mamute. 
This is a open source question and answers engine: http://www.mamute.org/.

**Comment by Turini** [comment]
closing here. thanx for bringing this out, @masumcse1
