### ISSUE TITLE
Adding a method 'include' to receive Enum

### ISSUE THREAD

**Issue by pwener** [caelum/vraptor4#1040]
I stared at with follow code:

``` java
	result.include(FieldMessage.SUCCESS.toString(), "Requirement succesfully registered.");
	result.nothing();
```
My enum are:
``` java
public enum FieldMessage {
	SUCCESS("message-success"), 
	ERROR("message-error");
	
	private final String fieldName;
    
	private FieldMessage(final String fieldName) {
		this.fieldName = fieldName;
	}

	@Override
	public String toString() {
		return fieldName;
	}	
```

So, i thought, why not include a method with argument Enum to facilitate this called?

**Comment by lucascs** [comment]
Problem is that the straightforward string for the enum is the `name()`... So it would be equivalent something like
```java
result.include("SUCCESS", "Requirement...");
```

In you case you could replace the enum with a constants class:

```java
public final class FieldMessage {
   public static final String SUCCESS = "message-success";
   public static final String ERROR = "message-error";

   private FieldMessage() {} // so nobody can instantiate this class
} 
```
kinda java old school, but works.

**Comment by pwener** [comment]
Interesting, works fine but I thinking about use of polymorphism to solve that with  a method into DefaultResult which receives Enum object. And yes, right way would be using name(). You think unnecessary?
