### ISSUE TITLE
Tag unordered list

### ISSUE THREAD

**Issue by alandamatta** [caelum/vraptor4#1041]
Boa tarde.
Estou iniciando com vraptor agora, recém adquirido o livro da casa do código e estou com problema aparentemente simples, mas não sei como resolve-lo,
Ao usar um forEach para mostrar os dados de uma lista, na hora de renderizar no browser, ele está pulando uma linha, ou seja, ele mostra o retorno depois uma linha em branco e assim sucessivamente.

Andei dando uma procurada no tio google, mas não achei nada. =[
Poderia me dar uma ajuda?

**Comment by pwener** [comment]
É preciso ver o código, algumas coisas que podem ser:
- Alguma propriedade css, está a utilizar de algum framework? Use o F12 para ver as propriedades css utilizadas no local.
- Alguma tag perdida, tipo <br>. Acontece de as vezes ela está fora do display, será que não?

Enfim, não sei se aqui seria o melhor lugar pra resolver sua dúvida, aconselho o[ forúm guj.com.br](guj.com.br).

**Comment by angeliski** [comment]
Olá @alandamatta, você resolveu seu problema? Pode fechar essa issue?

**Comment by alandamatta** [comment]
Sim, foi resolvido!
Obrigado!

**Comment by angeliski** [comment]
@Turini , Essa issue pode ser fechada. :)

**Comment by Turini** [comment]
fechando. obrigado @angelisk
