### ISSUE TITLE
site: http://questions.vraptor.org

### ISSUE THREAD

**Issue by mariojp** [caelum/vraptor4#1047]
While accessing:
http://questions.vraptor.org 
Show:
502 Bad Gateway
nginx/1.4.6 (Ubuntu)

**Comment by Turini** [comment]
thank you for reporting this, @mariojp! i'll take a look asap

**Comment by Turini** [comment]
@janaparadiso will work here

**Comment by angeliski** [comment]
that problem persists

**Comment by Turini** [comment]
@angeliski we just need to remove this link, questions.vraptor.org will no longer be used.
would you like to send us a PR?

**Comment by angeliski** [comment]
Ok @Turini

**Comment by Turini** [comment]
closed by https://github.com/caelum/vraptor4/pull/1082
