### ISSUE TITLE
Inconsistent handling of parent/child class converters.

### ISSUE THREAD

**Issue by smbell** [caelum/vraptor4#1059]
If I have an Animal class with several subclasses (Cat, Dog, Frog, etc.) and I create a converter as such.
```java
@Convert(Animal.class)
@ApplicationScoped
public class AnimalConverter implements Converter<Animal> {
    ...
}
```
That works correctly and allows me to convert my animal classes. The problem comes in when I need a special case for Dog and I want to write a DogConverter. Right now if I have both an AnimalConverter and a DogConverter the behavior will depend on which class is loaded first in the classpath.
```java
@Convert(Animal.class)
@ApplicationScoped
public class AnimalConverter implements Converter<Animal> {
    ...
}

@Convert(Dog.class)
@ApplicationScoped
public class DogConverter implements Converter<Dog> {
  ...
}
```
If DogConverter is loaded first then both converters will be loaded in the vraptor DefaultConverters class. Attempts to convert a Dog class will use the DogConverter while all other animal types will use the AnimalConverter. This is because when DefaultConverters loads the AnimalConverter it looks for existing converters in the findConverterType method:
```java
private Class<? extends Converter<?>> findConverterType(final Class<?> clazz) {
	for (Class<? extends Converter<?>> current : classes) {
		Class<?> boundType = current.getAnnotation(Convert.class).value();
		if (boundType.isAssignableFrom(clazz)) {
			return current;
		}
	}

	logger.debug("Unable to find a converter for {}. Returning NullConverter.", clazz);
	return NullConverter.class;
}
```
If DogConverter is loaded first the attempt to load AnimalConverter will not find it because Animal is not assignable to Dog, however if AnimalConverter is loaded first Dog is assignable to Animal and the failure condition for duplicate Converters is triggered:
```java
if (!currentConverter.equals(NullConverter.class)) {
		int priority = getConverterPriority(converterClass);
		int priorityCurrent = getConverterPriority(currentConverter);

		checkState(priority != priorityCurrent, "Converter %s have same priority than %s", converterClass, currentConverter);
```

The code should work the same independent of class load order. It would be a small modification to update the code to be both consistent and support parent/child converters.

Update the findConverterType method as follows:
```java
private Class<? extends Converter<?>> findConverterType(final Class<?> clazz) {
    Class<? extends Converter<?>> found = null;
    Class<?> foundType = null;
	for (Class<? extends Converter<?>> current : classes) {
		Class<?> boundType = current.getAnnotation(Convert.class).value();
		if (boundType.equals(clazz)) {
			return current;
		}
        if (boundType.isAssignableFrom(clazz)) {
            if (foundType == null || foundType.isAssignableFrom(boundType)) {
                foundType = boundType;
                found = current;
            }
	}

    if (found != null) {
        return found;
    }
	logger.debug("Unable to find a converter for {}. Returning NullConverter.", clazz);
	
    return NullConverter.class
}
```

Then modify the checkstate in the register method from:
```java
 checkState(priority != priorityCurrent, "Converter %s have same priority than %s", converterClass, currentConverter);
```
to
```java
Convert currentType = currentConverter.getAnnotation(Convert.class);
checkState(priority != priorityCurrent || !type.value().equals(currentType.value()), "Converter %s have same priority than %s", converterClass, currentConverter);
```

**Comment by Turini** [comment]
Hi @smbell, thanks for investing time digging deep this issue.
would you like to send us a pull-request using the proposed solution?

**Comment by smbell** [comment]
Will do. Might take me a bit to get to it. Hopefully not more than a couple weeks.

**Comment by Turini** [comment]
awesome, sounds great to me! please let me know if you need any support

**Comment by smbell** [comment]
Pull request has been created. https://github.com/caelum/vraptor4/pull/1060

**Comment by Turini** [comment]
closing here since https://github.com/caelum/vraptor4/pull/1060#issuecomment-211062184 was merged. Thank you again, @smbell
