### ISSUE TITLE
adding in cookbook menu the page about @ConversationScoped 

### ISSUE THREAD

**Issue by angeliski** [caelum/vraptor4#1062]
I saw now that when I created the cookbook I did not put in the cookbook menu. The link is accessible by the url, but not is visible in the menu page.

**Comment by Turini** [comment]
Ops. Do you want to send us a PR adding a link for the cookbook, @angeliski?

**Comment by angeliski** [comment]
Yes! I will configure the project locally. 
I always get the error "Your Ruby version is 2.1.4, but your Gemfile specified 2.0.0" when I try configure my environment. You know why?
I don't know about Ruby and suspect the Gemfile lock the Ruby version, but my question is: The only resolution is change the Ruby version? Just curiosity even.

**Comment by Turini** [comment]
humm, I'm not sure (not a ruby expert as well). I'll take a look soon

**Comment by Turini** [comment]
closing here since PR was merged into master. thanks again, @angeliski
