### ISSUE TITLE
Error ao enviar objeto formato json para VRaptor

### ISSUE THREAD

**Issue by GiovaniSantos93** [caelum/vraptor4#1068]
Olá,

Estou precisando de uma força com este problema relatado por mim no GUJ: http://www.guj.com.br/t/error-ao-enviar-objeto-formato-json-para-vraptor/327848.

Abs.

**Comment by Turini** [comment]
Oi @GiovaniSantos93 

Você pode abrir um tópico em nossa lista de discussões em português?

O link é: https://groups.google.com/forum/#!forum/caelum-vraptor
