### ISSUE TITLE
Deploying error on Tomcat 7 (4.2.0-RC4) with JVM 1.7

### ISSUE THREAD

**Issue by carlosspohr** [caelum/vraptor4#1073]
Hi there,

I've updated Vraptor to **4.2.0-RC4**, and now I'm getting this error during tomcat startup:

https://gist.github.com/carlosjrcabello/167178813fd1004d660745c5a28803d1

Previows release **4.1.0.Final** seems OK, however, it contains some related bug fixed in newer releases. 

My app, just consumes logics from a RMI based app, his facades through local RMI connection, and doesn't have core overrides. My doubt about it is, do I have to update some dep lib (as weld) at pom besides vraptor ?

Does anyone here ran 4.2.0-RC4 on JVM 1.7\* ?

**Infos**

Our internal servers has same configuration of production servers, except that I've upgraded JVM to **1.8.0.66**. I'm thinking that some of libs for instance contains code that is only for JVM 1.8, such as Paranamer with parameters information method to scan methods' var names.

> java version "1.8.0_66"
> Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
> Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Production server - configurations**
Tomcat 7.0.69

> java version "1.7.0_80"
> Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
> Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Comment by pwener** [comment]
What is the version of tomcat in dev?

**Comment by carlosjrcabello** [comment]
4.2.0 rc4
