### ISSUE TITLE
VRaptor : Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by fabianoalmeida** [caelum/vraptor4#1085]
Olá pessoal.

Estou tentando criar uma aplicação usando o VRaptor com o JBoss 7.1.1 e estou recebendo uma mensagem de erro:

> java.lang.UnsupportedClassVersionError: br/com/caelum/vraptor/VRaptor : Unsupported major.minor version 51.0

Para maiores detalhes do log inteiro do erro, eu criei um [gist](https://gist.githubusercontent.com/fabianoalmeida/45de91b3bcbfa878e94c6cb780acbc2f/raw/51d332bb776c3538a2ba1f54a6f7b7c6f7d17b45/jboss-as-711-vraptor-error-log) para isso.

Tentei modificar o Build Path do projeto da JRE 1.6, 1.7 e 1.8 e o erro persiste. Será que estaria faltando alguma configuração para que consiga fazer funcionar esse projeto no JBoss?

Obrigado de antemão.

**Comment by dilnei** [comment]
Jboss 7.1.1 é com Java7, ou use uma versão anterior do Vraptor ou usa um Wildfly que já é com Java 8 e JavaEE7

**Comment by fabianoalmeida** [comment]
@dilnei obrigado pela resposta.

Como pontuei, também tentei com o Java 7 e mesmo assim a mensagem de erro é apresentada, entende?

Vou tentar utilizar uma versão mais antiga do VRaptor então.

**Comment by dilnei** [comment]
Pelo que lembro quando trabalhei com a versão 7.1.1 do jboss + Vraptor tinha problemas com o CDI e a versão do WELD que já não me recordo bem, mas eu lembro que eu usava um plugin que tinha sido criado na época pelo @garcia-jj(uns dos commiters do Vraptor) para obter a instância do BeanManager, funcionava bem mas com Vraptor 3x porque acho que o 4 ja era com JavaEE7 e usava CDI 1.2, mas embora eu tenha relatado isso o seu ero é referente a compilação em versões diferentes do Java.

**Comment by fabianoalmeida** [comment]
@dilnei muito obrigado. Usando o WildFly esses problemas não mais ocorreram.
