### ISSUE TITLE
Problem in session replication cluster (Wildfly 10.1.0.Final domain mode)

### ISSUE THREAD

**Issue by jslsolucoes** [caelum/vraptor4#1089]
When wildfly cluster try to replicate session the following exceptions occurs : 

`[Server:host1] Caused by: org.infinispan.commons.marshall.NotSerializableException: br.com.caelum.vraptor.validator.MessageList
[Server:host1] Caused by: an exception which occurred:
[Server:host1] 	in field messages
[Server:host1] 	in object java.util.HashMap@2325ee0c
[Server:host1] 	in object org.wildfly.clustering.marshalling.jboss.SimpleMarshalledValue@2325ee0c
[Server:host1] 	in object org.infinispan.commands.write.PutKeyValueCommand@9880eb17
[Server:host1] 	in object org.infinispan.commands.tx.PrepareCommand@a6ec3bc0
[Server:host1] '

Vraptor version : 4.2.0-RC5

Any ideias ?

**Comment by Turini** [comment]
@felipeweb just fixed it on #1090. will be available in the next release

thank you, guys
