### ISSUE TITLE
Assembly.xml does not exist

### ISSUE THREAD

**Issue by Rickpariz** [caelum/vraptor4#1105]
I have been facing problems while trying to run vraptor4 with NetBeans and Tomcat8. That's what I have:

Total time: 9.227s
Finished at: Wed Jan 17 19:56:58 BRST 2018
Final Memory: 15M/224M
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.3:assembly (default) on project vraptor-produtos: Error reading assemblies: Error locating assembly descriptor: assembly.xml

[1] [INFO] Searching for file location: C:\Users\bahia\Documents\estudos\Alura\desenvolvimento-web-com-vraptor-4-master\assembly.xml

[2] [INFO] File: C:\Users\bahia\Documents\estudos\Alura\desenvolvimento-web-com-vraptor-4-master\assembly.xml does not exist.

[3] [INFO] File: C:\Users\bahia\Documents\estudos\Alura\desenvolvimento-web-com-vraptor-4-master\assembly.xml does not exist.
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Turini** [comment]
it says:

>Error locating assembly descriptor: assembly.xml

were you able to verify that this file is in your project?

see:
https://github.com/caelum/vraptor4/blob/master/vraptor-blank-project/assembly.xml

if I'm not wrong it only happens on Netbeans, but might work if you manually add the file

**Comment by Rickpariz** [comment]
I'll check

**Comment by Rickpariz** [comment]
I got it. Thank you.

**Comment by Turini** [comment]
awesome. let us know if you need any further help (;
