### ISSUE TITLE
Não utilizar paginas de retorno de erro

### ISSUE THREAD

**Issue by CoderSquirrel** [caelum/vraptor4#1112]
Existe uma maneira de alterar para quando der erro (500,409,404) nao utilizar aquela pagina de retorno?

possuo esse código:

`

		try {

			dao.salvar(selo);
			result.use(Results.json()).withoutRoot().from(selo).serialize();
			result.use(Results.status()).ok();
		} catch (Exception e) {

			if (e.getCause().getMessage().contains("ConstraintViolationException")) {
				 result.use(Results.json()).from(selo).recursive().serialize();
				 result.include("data", selo);
				 result.use(Results.status()).conflict();
				

			}

		}

`

porem a mensagem no front recebida é a pagina, portando meu angular da o erro

`
angular.min.js:107 TypeError: Cannot read property 'data' of undefined
    at angular-resource.min.js:11
    at angular.min.js:118
    at m.$eval (angular.min.js:132)
    at m.$digest (angular.min.js:129)
    at m.$apply (angular.min.js:133)
    at g (angular.min.js:87)
    at L (angular.min.js:91)
    at XMLHttpRequest.A.onload (angular.min.js:92)`

Alguem fez algo para resolver isso? Nao consegui achar muita coisa, talvez eu tambem nao saiba a maneira certa de procurar

**Comment by cassunde** [comment]
Como veio a resposta na requisição?

**Comment by CoderSquirrel** [comment]
@cassunde perdão esqueci de fechar o issue, era culpa de um interceptor que eu nem lemrava que tinha no js heheh
