### ISSUE TITLE
Localizar Environment Properties

### ISSUE THREAD

**Issue by andersonscherrrer** [caelum/vraptor4#1133]
Estou tentando colocar as dependencias do projeto na pasta lib do tomcat, ou seja todos os jars não ficam na pasta classes do .war, o problema é que o Environment não encontra os .properties. Então eu pesquisei e resolvi extender o DefaultEnvironment, e também tentei implementar Environment, mas sem sucesso alguma sugestão?

**Comment by IvoSestren** [comment]
Qual a sua dificuldade em estender a classe?

Fiz isto em alguns projetos meus e funcionaram perfeitamente.

**Comment by andersonscherrer** [comment]
Putz, agora eu desfiz tudo pois, não consegui implementar. Era assim, se eu colocava os .jar direto na lib do tomcat, o Vraptor não encontrava os .properties do projeto, e se eu Exteendia DefaultEnvironment ele não exectuava esta classe "ignorava".

**Comment by IvoSestren** [comment]
Quando você estender a classe, tenta colocar um @Specializes em cima dela.
Assim força ao CDI injetar esta classe em vez da Default.

Em qui, 27 de set de 2018 às 15:38, Anderson Scherrer <
notifications@github.com> escreveu:

**Comment by andersonscherrrer** [comment]
Código ficou assim:

`@Specializes
@ApplicationScoped
public class CustomEnvironment extends DefaultEnvironment {
}`

Copiei tudo que estava na DefaultEnvironment e coloquei ali. Aí rodando a aplicação no Tomcat:

No active contexts for scope type javax.enterprise.context.RequestScoped

**Comment by andersonscherrrer** [comment]
Ele continua tentando pegar a key do DefaultEnvironment:

Caused by: java.util.NoSuchElementException: Key brutauth.allowAll not found in environment development
	at br.com.caelum.vraptor.environment.DefaultEnvironment.get(DefaultEnvironment.java:176)
	at br.com.caelum.vraptor.environment.DefaultEnvironment$Proxy$_$$_WeldClientProxy.get(Unknown Source)
	at auth.roles.ShouldBeLoggedRule.isAllowed(ShouldBeLoggedRule.java:51)

**Comment by andersonscherrrer** [comment]
Tentei assim também:
`
@ApplicationScoped
@Priority(Interceptor.Priority.LIBRARY_BEFORE + 10)
public class CustomEnvironment implements Environment {`

Tentei injetando especificadamente: 
@Inject
	private CustomEnvironment env;

E nada

**Comment by andersonscherrer** [comment]
Deu certo, agora o ResourceBundle não encontra as messages.properties.

**Comment by andersonscherrer** [comment]
Consegui, aqui, valew. Era só o @Specializes mesmo, e sobrescrever também o comportamento do ResourceBundle.
