### ISSUE TITLE
Custom converters

### ISSUE THREAD

**Issue by nykolaslima** [caelum/vraptor4#894]
It would be nice to define custom converters.

e.g. I could use more than one strategy to deserialize dates:

```
@Get
public void withIsoDate(@Converter(ISOConverter.class) Date date) {...}

@Get
public void withDefaultDate(Date date) {...}
```

**Comment by renanigt** [comment]
Hi caelum/vraptor4,

I&#39;d like to include you in my network to share updates and stay in touch.

- Renan

Confirm that you know Renan: https://www.linkedin.com/e/v2?e=0-ihdt1paa-61&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=0fx0zzeG&invitationId=6075009319022194688








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ihdt1paa-61&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGMAHRYlynGfAAAAVE7E6GhEWI-xv_Zpe0NDqifb7Teo4amHBYLy1sRsp0Ee5DI2JnbMwOydPVqnYvx0yXZMxc_K3tX6-K-FPT1VjWg6il3VopGV04Tc3fdC4LGau-D2oZ7YpW94Ii9wr6NPSpehtAgtCr11vCPBzri1UjANpMKg7Waxu7ZJFnJOMUrUfcI2Lme&eid=0-ihdt1paa-61


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ihdt1paa-61&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by renanigt** [comment]
Renan Montenegro would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=x4rlp0-ihncweet-4f&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=0fx0zzeG&invitationID=6075009319022194688

View Renan Montenegro&#39;s profile: https://www.linkedin.com/e/v2?e=x4rlp0-ihncweet-4f&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=0fx0zzeG&invitationID=6075009319022194688





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=x4rlp0-ihncweet-4f&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=x4rlp0-ihncweet-4f&loid=AQENCBvdtW94MAAAAVFeHJF1rfPeozoS3UUHJjIQvLte9qslSrcrmeldO3T1gsVe_QjlyVaIG74XXlRMImW9CowseP-Q3gpI9UszR98QlyD3rD7PkW7sEE79BtqaEb05Qvhy_3lkgdZMMuMoIwzb7BMZFG64WO_0-Qwd4lvijdLEkluPdH-3MOjk4wizfg7r9AU9

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=x4rlp0-ihncweet-4f&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
