### ISSUE TITLE
Fluent validations

### ISSUE THREAD

**Issue by nykolaslima** [caelum/vraptor4#896]
In VRaptor3 we could do validations like this:

```
validator.checking(new Validations() {{
that(nome != null, "name", "validation.required");
//And we can do validations based on other validations
if(that(idade != null, "idade", "validation.required")) {
    that(idade > 18, "idade", "validation.minAge");
}
}});
```

In VRaptor4, we don't have this fluent validation. And there is no easy way to do validations based on other validations (like age validation on the above code).

Why do we removed this fluent validation? There is no easy way to chain validations with the actual implementation.

**Comment by renanigt** [comment]
Hi caelum/vraptor4,

I&#39;d like to include you in my network to share updates and stay in touch.

- Renan

Confirm that you know Renan: https://www.linkedin.com/e/v2?e=0-ihdt1r45-5x&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=xD5XISFv&invitationId=6075009318032326656








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ihdt1r45-5x&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHKTIwerB5g3QAAAVE7E342CnNeDh7sCrR5Yh0IkkRQkmCQbbUezCCeImCoinJfj9IwG-1gF93IKnOshN196n-phsYYKepDPXilpgJ1tR3JC-jgcjv2y6Hq3FAOdxd0lv9W83b9HPtYlejeumBjJgvTsRRKYLOLs_NGsnL5YD2jtUYYKmv4uv6amSFFCkLyuKZa&eid=0-ihdt1r45-5x


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ihdt1r45-5x&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by renanigt** [comment]
Renan Montenegro would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=4685ob-ihncwg9b-3t&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=xD5XISFv&invitationID=6075009318032326656

View Renan Montenegro&#39;s profile: https://www.linkedin.com/e/v2?e=4685ob-ihncwg9b-3t&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=xD5XISFv&invitationID=6075009318032326656





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=4685ob-ihncwg9b-3t&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=4685ob-ihncwg9b-3t&loid=AQG1_RnNE2xOcgAAAVFeHYJ9-RGwmy7kB7dwwyYUX1an3K12G1CTyQ7fdlqxHlg57VhQwvJinY6Oth_8rVyXVD0Q_-Jruge2h1jkTUECqxhViopLLj8jVd_NQE1S1AXv5eV_xJKvG6uj_BUsddi80hamKi_oMN2XOWmPaQ2mB8ry6jmtj24drFnMMjxiAX6TOITk

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=4685ob-ihncwg9b-3t&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
