### ISSUE TITLE
Bug when importing blank-project zip to IDE

### ISSUE THREAD

**Issue by Turini** [caelum/vraptor4#904]
on the zip generated by `mvn package`, the `WEB-INF/classes` folder contains an `IndexController.class`, so this controller still registered even droping the java 
file from project. I think probably the same occurs with `META-INF/beans.xml` file

**Comment by rsaraiva** [comment]
By default, 'mvn package' adds class files only in 'target' folder. I find the Eclipse compilation is adding this class files in ./src/main/webapp/WEB-INF/classes.

The command 'mvn clean' cleans only the 'target' folder too. But it is possible configure additional directories to clean:

http://maven.apache.org/plugins/maven-clean-plugin/examples/delete_additional_files.html

**Comment by Turini** [comment]
thanks @rsaraiva, I'm taking a look on this (sorry my delay).

**Comment by lucas-felix** [comment]
I took a look on this with @Turini and we couldn't reproduce the bug.

It seems that this not is occurring anymore. I think you can close this issue @Turini.

**Comment by Turini** [comment]
yes, thank you for investing time on this issue @lucas-felix
