### ISSUE TITLE
Can't catch specific exception in Interceptor

### ISSUE THREAD

**Issue by nykolaslima** [caelum/vraptor4#911]
```
@AroundCall
    public void intercept(SimpleInterceptorStack stack) throws InterceptionException {
        try {
            stack.next();
        } catch (MyException e) {
            System.out.println("error");
        } 
    }
```

This code does not work because VRaptor is encapsulating `MyException` in one `ApplicationLogicException`.

**Comment by Turini** [comment]
I've just oppened a PR https://github.com/caelum/vraptor4/pull/945 with this suggestion. 

What do you think @lucascs @nykolaslima `@everyone`?

**Comment by nykolaslima** [comment]
@Turini it doesn't have been released in the RC2 version?
which is the most recent available version?

**Comment by Turini** [comment]
@nykolaslima I'm so sorry about my delay to answer this thread. That was an insane week.
It'll be released as soon as possible -- I'm planning to do that this week, I'll let you know ;)

**Comment by nykolaslima** [comment]
No problem @Turini. Thank you!

**Comment by renanigt** [comment]
Hi caelum/vraptor4,

I&#39;d like to include you in my network to share updates and stay in touch.

- Renan

Confirm that you know Renan: https://www.linkedin.com/e/v2?e=0-ihdt1q2v-a&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=1XiVMCa4&invitationId=6075009319286427648








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ihdt1q2v-a&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQH51ye9wZFQqQAAAVE7E2ACL-axGo6togc6AmJDKlUYqJ1xuRJSMdSJgkiJyzKw3PjGINLi1AzvzqbKtyo3H1Tm0HA5x1NIeXZ6j-MQcP7eJX-POLleRTYGd1SZg1ima_hM45F3HSzur3QEbNaxm0DZEijtRbononR5WvpighScUCaPOMZE1GdhWFjUu0qXveCi&eid=0-ihdt1q2v-a


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ihdt1q2v-a&a=customerServiceUrl&ek=invite_guest

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by renanigt** [comment]
Renan Montenegro would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-vkbt7q-ihncxxup-25&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=1XiVMCa4&invitationID=6075009319286427648

View Renan Montenegro&#39;s profile: https://www.linkedin.com/e/v2?e=-vkbt7q-ihncxxup-25&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=1XiVMCa4&invitationID=6075009319286427648





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-vkbt7q-ihncxxup-25&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-vkbt7q-ihncxxup-25&loid=AQE4E1DLaAeFRgAAAVFeHogdxtow1U1H1wIZzBjYt0Lk27sJtqmeYQ24FP8EsgmjpRmlKverBbzp1z5tqHeI2lGtITD_z3KGWvmi4kIFGo252hx1kpDqIYWGD_TsKqHva2cnXRxpjCqNpe6Z9XVv2vFKQcXAh-RhZOnrVsnet3sBSlpwd19me7CRGFjMh2iTsXfe

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-vkbt7q-ihncxxup-25&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by renanigt** [comment]
Renan Montenegro would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-vkbt7q-ihxd610w-gl&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=1XiVMCa4&invitationID=6075009319286427648

View Renan Montenegro&#39;s profile: https://www.linkedin.com/e/v2?e=-vkbt7q-ihxd610w-gl&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=1XiVMCa4&invitationID=6075009319286427648





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-vkbt7q-ihxd610w-gl&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-vkbt7q-ihxd610w-gl&loid=AQGr70i5ZX9ewgAAAVGClveMC5pmneKLcJkmVsxXiOaw1yR9DYoE5-qt-CcF0PulX4zskNbONFPwchLdYBmSWXYVaOCMwoW8FhxLsQkaZ4JWflZKAGfUW2FkzN_FrltxLGsbj5a7XUuaSWjpKrv0qWxzUzW6ovvuJgtNt2tgi4U57p6efr5V6FNDYdrqFIDaAhcl

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-vkbt7q-ihxd610w-gl&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2015 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
