### ISSUE TITLE
automatic deploy of vraptor-site

### ISSUE THREAD

**Issue by Turini** [caelum/vraptor4#923]
it would be nice to find a way to update it with new commits, just like jekyll does

**Comment by luiz** [comment]
The only way I can think of right now is to create a commit hook that each developer will need to add to his/hers `.git` folder. What do you think of it? Any other ideas?

**Comment by Turini** [comment]
I like it. It sounds enought to me (and i think it's the only option anyway :)

**Comment by csokol** [comment]
We could also create a jenkins job.

Em 8:35 qua, 21/01/2015, Rodrigo Turini <notifications@github.com> escreveu:

**Comment by luiz** [comment]
Using Caelum's Jenkins? That sounds good. But I think that a Git hook would be more transparent to anyone collaborating to the project and would be easier to maintain. The only downside I can see is the need to configure it the first time you clone the project. What do you think?

**Comment by Turini** [comment]
> The only downside I can see is the need to configure it the first time 
you clone the project.

A simple instruction at vraptor-site's README would be enought for it :)

**Comment by csokol** [comment]
When we merge a PR using github this hook wont be executed, rigth?

Em 9:02 qua, 21/01/2015, Rodrigo Turini <notifications@github.com> escreveu:

**Comment by luiz** [comment]
Hmmm... That's right. We would need to merge it manually... Now Jenkins sounds more attractive :)
I'll include a step to build and deploy the site there, if no one is against it.

**Comment by Turini** [comment]
:+1:

**Comment by csokol** [comment]
Another option is to develop our own github hook:
https://developer.github.com/v3/repos/hooks/

Is harder to develop but I think we can have fun doing it :-)

**Comment by luiz** [comment]
I took a look at webhooks documentation and it sounds great! However, we will still need a server to receive the payload and build the site, so I think we are good with Jenkins. It won't be as fun, but I think it doesn't fit well here... :(
