### ISSUE TITLE
Controller generico

### ISSUE THREAD

**Issue by jeancrbecker** [caelum/vraptor4#930]
Galera alguem conseguiu criar um controller generico usando VRaptor 4.1 ? Quando utilizo metodos que recebem objetos como parametro ele não faz o reflection corretamente e acaba me retornando uma instancia de gson, agora quando incluo o tipo especifico da classe funciona sem problemas, ele apenas não reconhece quando é um tipo generico, precisaria fazer um interceptor ou um observer mas não tenho ideia de como implementar.

Minha controller generica:

```
public abstract class GenericController<T> {

    protected GenericService genericService;
    protected Result result;
    private Class<T> entityClass;

    public GenericController() {
    }

    @Inject
    public GenericController(Class<T> entityClass, Result result, GenericService genericService) {
        this.result = result;
        this.genericService = genericService;
        this.entityClass = entityClass;
    }

    @Permission(permissoes = {"usuario.logado"})
    @Get("")
    public void listar() {
        result.use(json()).withoutRoot().from(genericService.list()).serialize();
    }

    @Permission(permissoes = {"usuario.logado"})
    @Get("{id}")
    public void getByID(Long id) {
        result.use(json()).withoutRoot().from(genericService.find(id)).serialize();
    }
/**ESSE METODO NÃO FUNCIONA**/
    @Permission(permissoes = {"usuario.logado"})
    @Post("")
    @Consumes(value = "application/json", options = WithoutRoot.class)
    public void novo(T entity) {
        genericService.insert(entity);
        result.use(json()).withoutRoot().from("ok").serialize();
    }
/**ESSE METODO FUNCIONA**/
    @Permission(permissoes = {"usuario.logado"})
    @Put("")
    @Consumes(value = "application/json", options = WithoutRoot.class)
    public void salvar(Menu entity) {
        genericService.update(entity);
        result.use(json()).withoutRoot().from("ok").serialize();
    }
}

```

Minha controller especializada

```
@Controller
@Path("/menus")
public class MenuController extends GenericController<Menu> {

    private MenuService menuService;

    @Inject
    public MenuController(Result result, MenuService menuService) {
        super(Menu.class, result, menuService);
    }

    @Deprecated
    public MenuController() {

    }

}

```

**Comment by lucascs** [comment]
O problema está nesse método:

https://github.com/caelum/vraptor4/blob/master/vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/gson/GsonDeserialization.java#L179-L187

A gente precisa adicionar um teste que reproduz essa sua situação e ver se esse método retorna a classe correta. Quer tentar fazer isso?

**Comment by jeancrbecker** [comment]
Posso tentar sim, o que preciso fazer ?

**Comment by lucascs** [comment]
Entra nessa classe: https://github.com/caelum/vraptor4/blob/master/vraptor-core/src/test/java/br/com/caelum/vraptor/serialization/gson/GsonDeserializerTest.java

copia os seus dois controllers pra um dos pacotes de teste, passa pro teste o método problemático, e vê se o deserializer usa o tipo certo.

**Comment by jeancrbecker** [comment]
Não entendi muito bem o que fazer, comecei a usar o vraptor e o git a pouco tempo. Mas pela classe que você tinha passado eu coloq

**Comment by jeancrbecker** [comment]
Não entendi muito bem como fazer isso que você pediu, comecei a usar o git agora. Pelo classe que você tinha passado coloquei um observer  "@Observes ControllerFound" e percebi que o parameterTypes do method quando utiliza parametro genérico no controller vem java.lang.Object e não o tipo setado ao instanciar a classe.

**Comment by lucascs** [comment]
ele vai vir como object mesmo, pq ele é o T. 

nesse caso, a gente tem que ver que o generic type do cara é do tipo TypeVariable, e pegar o tipo do T da classe do controller, não do método. Tem idéia do que eu to falando?

Generics é bem zoado de fazer esse tipo de código, tem vários casos chatos o.o

**Comment by jeancrbecker** [comment]
Sim isso eu imaginei, por isso que eu disse que talvez tenha de usar um interceptor ou mesmo um observer, assim como vi que esse cara fez http://www.guj.com.br/java/221981-vraptor-3--genericcontroller-resolvido mas pelo jeito não funciona mais assim no VRaptor 4.

**Comment by lucascs** [comment]
Não precisa chegar a tanto, só mudar aquele método que eu tinha linkado lá em cima já era o suficiente.

Precisa corrigir ele pra retornar o tipo certo no seu caso. Por isso eu falei pra vc escrever um teste e mandar um Pull request pra corrigir isso no VRaptor =)

**Comment by jeancrbecker** [comment]
Se puder me dizer um link onde ensina e fazer isso, pois como eu disse comecei a usar hoje o github apenas para tentar descobrir a solução para meu problema, desde já agradeço.

**Comment by clairton** [comment]
Boa Noite.
Fiz um crud generico, está em
https://github.com/clairton/vraptor-crud/blob/master/src/main/java/br/eti/clairton/vraptor/crud/CrudController.java
e os testes em
https://github.com/clairton/vraptor-crud/blob/master/src/test/java/br/eti/clairton/vraptor/crud/CrudControllerTest.java
Espero que possa ajudar.

Atenciosamente
*Clairton Rodrigo Heinzen*
Bacharel em Sistemas de Informação
Especialista em Engenharia de Software
Desenvolvedor Java - Sicoob MaxiCrédito
*https://github.com/clairton <https://github.com/clairton>*

*https://www.facebook.com/clairton.rodrigo
<https://www.facebook.com/clairton.rodrigo>*

Em 28 de janeiro de 2015 19:26, jeancrbecker <notifications@github.com>
escreveu:

**Comment by lucascs** [comment]
Consegui escrever o teste que reproduz o bug. Vou ver se consigo corrigir agora =)

**Comment by lucascs** [comment]
Criei lá o Pull Request, quer que gere uma versão snapshot pra vc assim que for aceito?

o que dá pra fazer tb é vc copiar essa classe que mudou pro seu projeto, daí vai sobrescrever o componente padrão do VRaptor

**Comment by jeancrbecker** [comment]
Legal Lucas, show de bola, copiei a classe para meu projeto e tudo funcionou perfeito, quando sair um novo snapshot me avisa que ja vou atualizar pra ficar com o projeto atualizado. Muito obrigado pela ajuda.

**Comment by lucascs** [comment]
@jeancrbecker Tá lá:

ttps://oss.sonatype.org/content/repositories/snapshots/br/com/caelum/vraptor/4.2.0-SNAPSHOT/vraptor-4.2.0-20150129.134722-1.jar

Ou use a 4.2.0-SNAPSHOT no seu pom.xml ou coisa do tipo

**Comment by jeancrbecker** [comment]
Blz Lucas, muito obrigado.

Att.
--
Jean C. Becker
(41) 9921-8625 - jeancrbecker@gmail.com
JBKR - Tecnologia e Inteligência com foco no desenvolvimento de conteúdos
para WEB
Acesse : www.jbkr.com.br
*"É assim que se aprende o máximo, quando você está fazendo algo com tanto
entusiasmo que não nota o tempo passando"*

2015-01-29 11:50 GMT-02:00 Lucas Cavalcanti <notifications@github.com>:
