### ISSUE TITLE
Vraptor livraria faltando DefaultDS na JPA no Eclipse

### ISSUE THREAD

**Issue by hevellynnatasha** [caelum/vraptor4#934]
Bom dia Lucas,

Estou seguindo os passos do livro VRaptor, e encontrei a seguinte dificuldade na pag 17-18.
Ao ir em /ProjectsFacets, selecionar JPA , Further configurations .. 
![capturar](https://cloud.githubusercontent.com/assets/7150126/5992366/d69d5a98-aa0d-11e4-80ed-20a003855baa.PNG)
só aparece BIRT Classic Model.

- Ja instalei o Jboss, criei o usuario no Admin Console
- Instalei o JBoss Tools
- As paginas funcionaram como descreve no inicio da pag 17.

Any idea why that?

Se eu usar o Mysql, encontro problemas no acompanhamento do livro?

Thanks.

**Comment by lucascs** [comment]
Deveria funcionar com MySQL normalmente... A configuração do DefaultDS era
mais pra integrar o controle transacional do servidor.
Daí precisa usar o DataSource no próprio wildfly pra isso funcionar. Tenta
fazer sem configurar isso no JPA Facet (só deixa ela ativa) e ver se dá
algum erro.

Qualquer coisa dá um toque.

[]'s
Lucas Cavalcanti
livro de VRaptor: www.casadocodigo.com.br/products/livro-vraptor
github.com/lucascs
@lucascs

**Comment by Turini** [comment]
Ois. Estou fechando a issue, ta bem? Caso não tenha sido resolvido, você 
pode abrir uma thread em [nossa lista de usuários](https://groups.google.com/forum/#!forum/caelum-vraptor). Até mais, bons estudos.
