### ISSUE TITLE
Empty list at Json serialization from ArrayList

### ISSUE THREAD

**Issue by cleberangelo** [caelum/vraptor4#935]
Ao serializar json a partir de um ArrayList o método retorna uma lista vazia. Se utilizar LinkedList ao invés de ArrayList, funciona corretamente. Provável problema com o ArrayList.

public void vinculosJson(Long individuoId) {
    List<Vinculos> vinculosList = vdao.list(individuoId);
    //List<Individuos> individuosList = new ArrayList<>(); Não funciona, retorna json vazio
    List<Individuos> individuosList = new LinkedList<>();

    if (vinculosList != null) {
      for (Vinculos v : vinculosList) {
        Individuos i = idao.load(v.getVinculoId());
        individuosList.add(idao.load(v.getVinculoId()));
      }
    }

    result.use(Results.json())
    .withoutRoot()
    .from(individuosList)
    .exclude("arquivosList")
    .exclude("descricao")
    .serialize();
  }

**Comment by Turini** [comment]
@cleberangelo I'm trying to reproduce it, but it works for me with both `array` 
and `linked` list. Can you send us an sample of code with this bug happening?

**Comment by cleberangelo** [comment]
This happens to me with the code posted in the issue.

public void vinculosJson(Long individuoId) {
 List vinculosList = vdao.list(individuoId);
 //List individuosList = new ArrayList<>(); Não funciona, retorna json vazio
 List individuosList = new LinkedList<>();
if (vinculosList != null) {
  for (Vinculos v : vinculosList) {
    Individuos i = idao.load(v.getVinculoId());
    individuosList.add(idao.load(v.getVinculoId()));
  }
}

result.use(Results.json())
.withoutRoot()
.from(individuosList)
.exclude("arquivosList")
.exclude("descricao")
.serialize()
}

**Comment by Turini** [comment]
se você mudar de `List` pra `List<individuos>` funciona?

**Comment by cleberangelo** [comment]
I'll try this next week.

Best regards.

2015-02-20 10:42 GMT-02:00 Rodrigo Turini <notifications@github.com>:

**Comment by cleberangelo** [comment]
No. 
List<Individuos> individuosList = new ArrayList<>()
don't work.

I'm using Vraptor 4.1.4, aplication server is Wildfly 8.1.

**Comment by Turini** [comment]
but what about `List<individuos>`? such as:

```
List<individuos> individuosList = new ArrayList<>()
```

**Comment by cleberangelo** [comment]
Sorry. I forgot makdown for code. I'm using 
```
List<individuos> individuosList = new ArrayList<>()
```
and returned an empty json.

**Comment by Turini** [comment]
@cleberangelo, are you still facing this issue? 
I just did a lot of tests here, but I couldn't reproduce this issue. 
For me, both `Linked` and `ArrayList` are working.

**Comment by cleberangelo** [comment]
Ok man, it may be a local problem, maybe in my java virtual machine.
ArrayList and LinkedList has different internal allocation methods, so...
Forget the issue.

Best regards,
Cleber

2015-04-01 2:00 GMT-03:00 Rodrigo Turini <notifications@github.com>:

**Comment by Turini** [comment]
ok, thanks @cleberangelo
