### ISSUE TITLE
XStream Collections Serialize

### ISSUE THREAD

**Issue by rodzappa** [caelum/vraptor4#936]
The Xstream default behavior when serialize collections is put a PersistentBag tag in output instead of populate with data from collection objects.
It is desirable that the serialization of collection objects to be triggered by default or by setting.

**Comment by garcia-jj** [comment]
In this case you need to use `xstream:xstream-hibernate` artifact, that serialize/deserialize Hibernate collections properly.

**Comment by rodzappa** [comment]
Hi Otávio Garcia!

How to do the VRaptor register and use this artifact?

I put this into my pom.xml:

<dependency>
	<groupId>com.thoughtworks.xstream</groupId>
	<artifactId>xstream-hibernate</artifactId>
	<version>1.4.7</version>
</dependency>

But, hibernate collections is serialized as PersistentBag, yet.

**Comment by garcia-jj** [comment]
In the xstream faq have info about use it. http://xstream.codehaus.org/faq.html#Serialization_Hibernate. In this link you can see whats the converters to register.

Let us know if works properly for you.

**Comment by Turini** [comment]
@rodzappa did it work? don't forget to let us know about it :)

**Comment by Turini** [comment]
I'm closing here, please feel free to reopen it if this solution doen't solves the issue.
