### ISSUE TITLE
Problem in environment with concurrent access

### ISSUE THREAD

**Issue by nykolaslima** [caelum/vraptor4#972]
When you use the `Environment` for the first time, it tries to initialize in a lazy mode.

The problem is that if we have concurrent threads trying to access the `Environment`, this line could lead to `NoSuchKeyException` because the second thread will use an empty `Property` object.
https://github.com/caelum/vraptor4/blob/d5adfda037461d84c1a2a5d1c169b4a986371313/vraptor-core/src/main/java/br/com/caelum/vraptor/environment/DefaultEnvironment.java#L80

We could resolve this by making the lazy initialization syncronized. There is another better solution to this?

(@csokol identified the problem, thanks Chico)

**Comment by csokol** [comment]
Maybe we should synchronize only the code block between lines 80-85 and also double check if the properties attribute is null...

**Comment by Turini** [comment]
yes, it'd solve the issue and doesn't seem to be so costly.
But, just wondering, is the lazy initialization really necessary?

**Comment by Turini** [comment]
note: we could also manage env properties with CDI, 
using `Instance` to lazy initialize it, but looks like an unnecessary work

**Comment by csokol** [comment]
I don't know if it's that critical but it makes the bootstrapping of a vraptor application faster, but I'm not against removing this lazy initialisation. Removing it will also improve the code, removing some ugly null checks...

**Comment by nykolaslima** [comment]
But It will hit the IO every time it creates a `Environment` right? Maybe it'll be nice to lazy loading it.

**Comment by csokol** [comment]
I think the idea is to load the properties during application startup (in a
@PostConstruct for example)

**Comment by Turini** [comment]
exactly!

**Comment by nykolaslima** [comment]
The `@PostConstruct` could deal with concurrency?

**Comment by Turini** [comment]
the `@PostConstruct` will not be accessed for multiple threads, so we don't 
need to worry about that. IMO the gain of removing the ugly null checks is
greater than the lazy strategy (the prop will be loaded once, on the app startup).

**Comment by nykolaslima** [comment]
But the `DefaultEnvironment` is application scoped. So if we use the `@PostConstruct` it will be lazy loaded automatically, right?

**Comment by Turini** [comment]
yes, it'll be a passivation-capable bean (lazy loaded)

**Comment by nykolaslima** [comment]
Ok, I'll implement it.

**Comment by Turini** [comment]
:heart:
