### ISSUE TITLE
Default json serialization exclude null fields

### ISSUE THREAD

**Issue by robsonperassoli** [caelum/vraptor4#984]
Hello Everyone.

I'm having a issue with vraptor4 and want to discuss with you about the best solution.

The Gson serializer, by default excluce null fields from serialization, for example, if i have the following code:
```java
class Person {
    private String name;
    private Integer age;

    public Person(String name, Integer age) {
        this.name =  name;
        this.age = age;
    }

    public String getName(){
        return this.name;
    }

    public Integer getAge(){
        return this.age;
    }
}

Person john = new Person("John Smith", 15);
Person marie = new Person("Marie Claire", null);

result.use(Results.json())
    .withoutRoot()
    .from(Arrays.asList(john, marie))
    .serialize();
```

The json returned by this method is :
```json
[
	{
		"name": "John Smith",
		"age": 15
	},
	{
		"name": "Marie Claire"
	}
]
```

I want to know what you think of serialize this null fields? In a litle research i made, i see this is a default behavior in Jackson and JaxB and others frameworks.

In Gson if we want to serialize null, is necessary to call the serializeNulls() method in the GsonBuilder, this line is located in GsonBuilderwrapper:
```java
getGsonBuilder().serializeNulls().create()
```

**Comment by Turini** [comment]
Hi @robsonperassoli. IMO we'd continue excluding null fields from serialization,
just like the JAX-B and Jackson. But for sure we could make it easily configurable 
for users :) maybe adding a `serializeNulls()` on `Results#json`, just like this:
```
result.use(json()).serializeNulls().from(car);
```
Or providing an easy way to make it as default behavior for those who want to. 
What do you think?

**Comment by robsonperassoli** [comment]
Hi @Turini your solution is really great. This will help me a lot, and for sure will help others too.

I could do this and send a PR? What do you think?

**Comment by Turini** [comment]
Sure! It'd be great, @robsonperassoli :+1:

**Comment by Turini** [comment]
your PR was merged, @robsonperassoli! It'll be lanched soon
great work you did here, thanks agains for your issue and pull-request :+1:

**Comment by Turini** [comment]
cloed by #987

**Comment by robsonperassoli** [comment]
Great! Thanks for your help!
