### ISSUE TITLE
Our Gson and XStream converters should be alternatives

### ISSUE THREAD

**Issue by Turini** [caelum/vraptor4#996]
i.e: DateJsonConverter
so users can replace it by creating an alternative with higher priority

**Comment by leocwolter** [comment]
Is there any reason not to extend and specialize those?

**Comment by Turini** [comment]
it's just an extra alternative, and will keep the symmetry with our internal converters
http://www.vraptor.org/en/docs/converters/#overriding-core-converters
the use of alternatives is pretty recommended when you are changing the entire behavior of the bean :)

**Comment by leocwolter** [comment]
Fair enough
